### ISSUE TITLE
Introduction to Algorithmic Marketing - Not secure and no content

### ISSUE THREAD

**Issue by yamtimor** [flpezet/analytics-readings#4]
[Introduction to Algorithmic Marketing](https://algorithmic-marketing.online/) - Currently, there is no content on the site, and it is not secure.

**Comment by flpezet** [comment]
Hey  ! Thanks, I've just removed the link !  [695efde](https://github.com/flpezet/analytics-readings/commit/695efde60e47de66e021cdc0d03e4a6c27564404)
